[project]
name = "trades"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "loguru>=0.7.3",
    "pydantic>=2.10.6",
    "pydantic-settings>=2.6.1",
    "quixstreams>=3.9.0",
    "websocket-client>=1.8.0",
]
